BBBB BBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBB BBBBB gettext(u'Are you sure you want to block this user?') BBBBBBBB BBBBBXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
                BBBBB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Reason')  X
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX
                        XXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                BBBBBBBB BBBBBBBBBBBB
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Block') 
                        XXXXXXX XXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
                        XXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
