BBBB BBBBBBBBBBBB
BBBB BBBB
XXXXXXX
    XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB gettext(u'Unblock user') BBBB gettext(u'Block this user') BBBBBX
    XXXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBX
    XXXXXXXXXXXXXXXXXX
X
    BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBB BB BBBBBBBB
    BBBBB BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX
             XXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBXXXXXXXBBBBBX XXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXX XXXXXX X X X X XX XXXXXX
            BBBB
                XXXXX XXXXX XXXXXX X X X X XXXXXXXX
            BBBBB
        XXXXXX
    BBBBBBBB BBBBBBBBBB
XXXXXXXXX
