BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB
BBBB BBBBBBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXBBBBBBBB
BBBBB BBBBBBBBB X XXXXXXXXXXXBBBBBBBB
BB BBB BBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFFFFFXXXX
XXXXXXXX  gettext(u'Change password') 
XXXXXX
BBBBBBBB
BBBBB
BBBBB BBBBBBBXXXX XXXXXXXXXXXXXXXXXX
XXXXXBB BBBBBBBB XXXXXXXXXBBBBB XXXXXXXXXXXXX XXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
XXXXX
BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXBBBBB
BB BBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
    XXXX
BBBBB

XXX gettext(u'Enter a new password for the user <strong>%(username)s</strong>.') SSSSS S SSS SSSSSSSS SSS SSS SSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX

XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXX
  
   
  BB BBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXFFFFXXXXXX
  BBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
  
   
  BB BBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXFFFFXXXXXX
  BBBBB
XXXXXX

XXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Change password') X XXXXXXXXXXXXXXXX
XXXXXX

XXXXXX
XXXXXXXXXXXXX
BBBBBBBB
