# Generated by Django 3.2.9 on 2022-02-11 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر وی آی پی تا'),
        ),
    ]
