# Generated by Django 3.2.9 on 2022-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0007_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_request',
            field=models.BooleanField(default=False, verbose_name='درخواست نویسندگی'),
        ),
    ]
