# Generated by Django 3.2.9 on 2022-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/registration/adminlte/dist/img/user2-160x160.jpg', upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
