# Generated by Django 3.2.9 on 2022-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/user2-160x160.jpg', upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
