# Generated by Django 3.2.9 on 2022-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='images/user2-160x160.jpg', upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
