# Generated by Django 3.2.9 on 2022-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0006_auto_20220304_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='images/avatar5.png', upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
