BBBB BBBB
XXXX XXXXXXXXXXXXXXXX
  BBBBB BBBBBBB
    BBBBB BBBBBBBBBBBB
    BBB BBBBB BB BBBBBBBBBBBBB BBBBBBBBBBBXXXXXXX BBBBBBB BBBBBBBBBBBXXXXXXXXBBBBBBBBBBB
    BBBBBBBB
    BBBBB BBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Run the selected action') X XXXXXXXXXXXX XXXXXXXFFFFFFFFFXX gettext(u'Go') XXXXXXXXX
    BBBBBBBB
    BBBBB BBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXXXX
        BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXX XXXXXXX gettext(u'Click here to select the objects across all pages') XX gettext(u'Select all %(total_count)s %(module_name)s') SSSSSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX gettext(u'Clear selection') XXXXXXXXXXX
        BBBBB
    BBBBB
    BBBBBBBB
  BBBBBBBB
XXXXXX
