BBBB BBBB

BB BBBBBBBB
  BBB BBB BB BBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXBB BBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXXXXXXBBBBBXX
      XXXXXXX
        XXXXXXXXX
          XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'Models in the %(name)s application') SSSSSS SS SSS SSSSSSSS SSSSSSSSSSSXXXXXX
        XXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBB
          XXX XXXXXXXXXXXXXFFFFFBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
            BB BBBBBBBBBBBBBBB
              XXX XXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXX
            BBBB
              XXX XXXXXXXXXXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBB
              XXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Add') XXXXXXXXX
            BBBB
              XXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'View') XXXXXXXXX
              BBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Change') XXXXXXXXX
              BBBBB
            BBBB BBBBBBBBBBBBBBBB
              XXXXXXXXX
            BBBBB
          XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXX
  BBBBBB
BBBB
  XXX gettext(u'You don’t have permission to view or edit anything.') XXXX
BBBBB
