BBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB BBBBBBBB X BBBBB X  _('Django site admin') BBBBBBBB

BBBBB BBBBBBBB
XXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX _('Django administration') XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB
