BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX XXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXBBBBBBBB

BBBBB BBBBBBBXXXXBBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXBBBBBBBB

BB BBB BBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX BB BBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXXBBBBFFFFFFFFBBBBB
XXXXXXXX BB BBB gettext(u'Add %(name)s') SSS SSSSSSSSBBBBFFFFFFFFFFFFFFFFFFBBBBB
XXXXXX
BBBBBBBB
BBBBB

BBBBB BBBBBBBXXXX XXXXXXXXXXXXXXXXXX
BBBBB BBBBBBBBBBBB
BB BBBBBBBB BBB BBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBB
      BBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB
  XXXXX
BBBBBBBBBB
BBBBBBBB
XXXXX BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBB BBBBBBBBXXXXXXXXX BBBBBXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
XXXXX
BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXBBBBB
BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXBBBBB
BB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBB
    XX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
    XXXX
    
BBBBB

BBBBB BBBBBBBBBB
BBB BBBBBBBB BB BBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX
            BB BBBBBBBBB BBB BBB
                XXXXXXXXXXXXXXXXXX
            BBBBB
            XXXXXX
    XXXXXXXXX
BBBBBBBB


BBBBBBBBBBBBBBBBBBBBBB

XXXXXX
XXXXXXXXXXXXX
BBBBBBBB
