BBBB BBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBB
  XXXX
    BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
    XX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX
       gettext(u'Add %(name)s') SSS SSSSSSSS
    XXXX
  XXXXX
  BBBBB
BBBBBBBB
