BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB BBBBBBBBBB BBBBBB

BBBBB BBBBBBBBB
    
    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX  gettext(u'Delete multiple objects') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBB
    XXX gettext(u"Deleting the selected %(objects_name)s would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:") SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSS SS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSS SSSSSSS SSSSSSS SSSS SSSSSSSSSS SS SSSSSS SSS SSSSSSSSS SSSSS SS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB BBBBBBBBB
    XXX gettext(u'Deleting the selected %(objects_name)s would require deleting the following protected related objects:') SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSSS SSSSSSSS SSS SSSSSSSSS SSSSSSSSS SSSSSSS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB
    XXX gettext(u'Are you sure you want to delete the selected %(objects_name)s? All of the following objects and their related items will be deleted:') SSS SSS SSSS SSS SSSS SS SSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSSS SSS SS SSS SSSSSSSSS SSSSSSS SSS SSSSS SSSSSSS SSSSS SSSS SS SSSSSSSSXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX gettext(u'Objects') XXXXX
    BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
        XXXXFFFFFFFFFFFFFFXXXXX
    BBBBBB
    XXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    XXXXX
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFXX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Yes, I’m sure') XX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No, take me back') XXXX
    XXXXXX
    XXXXXXX
BBBBB
BBBBBBBB
