BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB

BBBBB BBBBBBBBB
    
    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFFFFFXXXX
XXXXXXXX  gettext(u'Delete') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBB
    XXX gettext(u"Deleting the %(object_name)s '%(escaped_object)s' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:") SSSSSSSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSSS SSSSSS SS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSS SSSSSSS SSSSSSS SSSS SSSSSSSSSS SS SSSSSS SSS SSSSSSSSS SSSSS SS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB BBBBBBBBB
    XXX gettext(u"Deleting the %(object_name)s '%(escaped_object)s' would require deleting the following protected related objects:") SSSSSSSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSSS SSSSSSS SSSSSSSS SSS SSSSSSSSS SSSSSSSSS SSSSSSS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB
    XXX gettext(u'Are you sure you want to delete the %(object_name)s "%(escaped_object)s"? All of the following related items will be deleted:') SSS SSS SSSS SSS SSSS SS SSSSSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS SSS SS SSS SSSSSSSSS SSSSSSS SSSSS SSSS SS SSSSSSSSXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX gettext(u'Objects') XXXXX
    XXXXFFFFFFFFFFFFFFXXXXX
    XXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    XXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXBBBBB
    BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Yes, I’m sure') XX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No, take me back') XXXX
    XXXXXX
    XXXXXXX
BBBBB
BBBBBBBB
