BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXBBBBBBBB

BBBBB BBBBBBBXXXXXBBBBBBBB

BBBBB BBBBBBBBB XXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Recent actions') XXXXX
        XXXX gettext(u'My actions') XXXXX
            BBBB BBB
            BBBBBBBBBBBBB BB BB BBBBBBBBB BBBBBBBB BBBB
            BB BBB BBBBBBBBB
            XXX gettext(u'None available') XXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBB
            XXX XXXXXXXBB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBXX
                BB BBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBB
                    
                BBBB
                    XX XXXXXXXXXXXX
                BBBBB
                XXXX
                BB BBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXX XXXXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXX
                BBBB
                    XXXXX XXXXXXXXXXX XXXXXXX gettext(u'Unknown content') XXXXXXX
                BBBBB
            XXXXX
            BBBBBB
            XXXXX
            BBBBB
    XXXXXX
XXXXXX
BBBBBBBB
