BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX

BBBBBBBB

BBBBB BBBBBBBBB XXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
XXXX
BBBBB

BB BBBBBBBBBBBBBBBBBBBBB
BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXXXXX
    
XXXX
BBBBBB
BBBBB

XXXX XXXXXXXXXXXXXXXXXX

BB BBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXXXXX
 gettext(u'You are authenticated as %(username)s, but are not authorized to access this page. Would you like to login to a different account?') 
    SSS SSS SSSSSSSSSSSSS SS SSSSSSSSSSSSS SSS SSS SSS SSSSSSSSSS SS
    SSSSSS SSSS SSSSS SSSSS SSS SSSS SS SSSSS SS S SSSSSSSSS SSSSSSSS

XXXX
BBBBB

XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX
    
     
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    
     
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
  XXXXXX
  BBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX gettext(u'Forgotten your password or username?') XXXX
  XXXXXX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Log in') XX
  XXXXXX
XXXXXXX

XXXXXX
BBBBBBBB
