BBBB BBBBBBBBBB
BBBB BBBB
XX XXXXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBBBB
BBB B BB BBBBBBBBBB
    BBBBBBBBBBBBBBBB BB B
BBBBBB
BBBBB
 BB BBBBBBBBBBBBBBB BB BBBBBBBBBB
BB BBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Show all') XXXXBBBBB
BB BBBBBBBBBB BBB BBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'Save') XXBBBBB
XXXX
