BBBB BBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
BBBBB BBBBBBBBBB
BB BBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save') X XXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB
BB BBBBBBBBBBBBBBBB BBB BBBBBBBB
    BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX
BBBBB
BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save as new') X XXXXXXXXXXXXXXXXXXBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save and add another') X XXXXXXXXXXXXXXXXXXXBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBB gettext(u'Save and continue editing') BBBB gettext(u'Save and view') BBBBBX XXXXXXXXXXXXXXXXXBBBBB
BB BBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXBBBBB
BBBBBBBB
XXXXXX
