# Generated by Django 3.2.9 on 2022-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog.ArticleViews', to='blog.IP_Address', verbose_name='بازدید ها'),
        ),
    ]
