# Generated by Django 3.2.9 on 2022-03-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220309_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.DeleteModel(
            name='ArticleViews',
        ),
    ]
