# Generated by Django 3.2.9 on 2022-03-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
