# Generated by Django 3.2.9 on 2022-03-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_article_hits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleViews',
        ),
    ]
