# Generated by Django 3.2.9 on 2022-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='blog.IP_Address', verbose_name='بازدید ها'),
        ),
    ]
