XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXX XXXXX X X
            XXXXX
        XX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXX XXXX X X XX X X XXXXXXXXXXXXX XXXX X
            XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X XXXXXXXXXXXXXXXXXX
            XXXXX X XXXXXXXXXX X XXX X XXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXXXX
    XXXXXXXXX
XXXXXXX
XXXXXXX