BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXBBBBBXX

XXXXXXXXX XXXXXXXXXXXXX XX
   BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
     XXXXFFFFFFFFXXXXX
   BBBB
     XXXXFFFFFFFFXXXXX
   BBBBB
   
   XXXXXXX
     XXXXXXXXXXX
       XXX XXXXXXXXXXXXXXXXXXXXXX
     BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
       BB BBB BBBBBBBBBBBBBBBBBBBBBB
         XXX XXXXXXXXXXXXXXBB BBBBBBBBBBBBBB XXXXXXXXBBBBBXXFFFFFFFF
         BB BBBBBBBBBBBBBBBXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXFFFFFFFFFXX XXXXXXXFFFFFFFFFXXBBBBB
         XXXXX
       BBBBB
     BBBBBB
     BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX gettext(u'Delete?') XXXXXBBBBB
     XXXXXXXXXXXXX

     XXXXXXX
     BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFXXXXXXXXXXXX
        BBBBB
        XXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXBBBBBX
             XXXXXBB BBB BBBBBBBBBBBBBBBBXXXXXBBBBBXX
        XXX XXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB
          
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Change') BBBB gettext(u'View') BBBBBXXXXBBBBB
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXX gettext(u'View on site') XXXXBBBBB
            XXXXBBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
            BBB BBBB BB BBBBBBBB
              BBB BBBBB BB BBBB
                BB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBB
            BBBBBB
          BBBBBB
          BBBBBBBBBBBB
        XXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
          BBB BBBB BB BBBBBBBB
            BBB BBBBB BB BBBB
              BB BBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBBBB
              XXXBB BBBBBBBBBBBBBBBB XXXXXXXXXXXXXXBBBBBX
              BB BBBBBBBBBBBBBBBBB
                  XXXXXXX
              BBBB
                  
                  
              BBBBB
              XXXXX
              BBBBB
            BBBBBB
          BBBBBB
        BBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        BBBBB
        XXXXX
     BBBBBB
     XXXXXXXX
   XXXXXXXX
XXXXXXXXXXX
  XXXXXX
XXXXXX
