BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBB BBBBB BBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXX
            BBBB
               XXXXXX XXXXX X XXXX
            BBBBB
BBBBBBBB BBBBBBBB


BBBBB BBBB
XXXX XXXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXX XXX XXXXXXX XXX
            FFFFFFFFFFFFFFF

            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX

            BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            BBBB
XXXX            XXX XXXXX XXXXXXX X XXXXXX XXXX XXXX XXXXX XXXXX XXX XXXXXXX XXXXXXX XXXX X XX XXXXX XXXX XXXXX XX XXXXXX XXX X XX XXXXXX XX XXXXX XXXX XXXXX XXXXXX XXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                        XXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXX XXXXXXXXXXXXXX
                XXXX                BB BBBBBBBBBBBBBBBBBXXX
                XXXX                BBBBXXX
XXXX                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXX X XXXXXXXXXXXXXXXXX
XXXX                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXX XXXXXXXXXXXXXXXXX
XXXX                BBBBBXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                       XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB


