BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB


BBBBB BBBB
    XXXXXXXX XXXX XXXXX XX
BBBBBBBB


BBBBB BBBBBBB
    XXXXXXXX XXXXXXX XXXXX XXX XXXXX XXXXXXXXX XXXX XXXXXX XXXXX
BBBBBBBB


BBBBB BBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX X
            XXXX
        XXXX
    XXXXXX
BBBBBBBB

