BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBB
    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
						BBBBBBBBBB
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
							XXXXX XXXXXXX XXXX
						XXXXXXX
						XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
							XX XXXXXXXXXXX XXXXXXXXXXXXXXX
						XXXXXXX
                        BB BBBBBBBBB
						XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXX XXX XXXXXXX
                            
							 FFFFFFFFFFFFFFFFFFFF
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
						XXXXXX

						XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXX
								XX XXXXXXXXXXX XXXXXXXXXXXXXX
							XXXXXXX
                            
							 FFFFFFFFFFFFFFFFFFFF
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXX
								XXXXXXXXX
							XXXXXX
                            BBBB
                                XXXXXXX XXXXX XXX XXX XXXX XXXXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                            BBBBB
						XXXXXX
					XXXXXXX
BBBBBBBB


