BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBB BBBBB BBBBBBBBBB
   XXXXX XXXXXXX
BBBBBBBB BBBBBBBB


BBBBB BBBB
XXXX XXXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
            XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXX
               FFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXX XXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB


