BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBB BBBBB BBBBBBBBBB
XXXXXXX XXXXXX
BBBBBBBB BBBBBBBB


BBBBB BBBB
XXXX XXXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBBB
        XXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXX X
                    XXXX XXXXX  X XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                    XXXXXXXXXXXXXXX XXXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBXX XXXX XXXX XXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXX XXX XXXXXXX XXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXX X XXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXX
         BB BBB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX  XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        BBBBB

    XXXXXX
XXXXXX
BBBBBBBB


