BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBB XXXXXX BBBBBBBB

BBBBB BBBB
XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXX XXXXX
                            XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XX XXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         FFFFFFFFFFFFFFFFFFFF
        BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXX
         FFFFFFFFFFFFFFFFFFFF
        BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXX
         FFFFFFFFFFFFFFFFFFFF
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXX
         FFFFFFFFFFFFFFFFFFFF
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXX
            XXXXXXXXX
        XXXXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBXX XXXX XXXX XXXX
        XXXXX
    XXXX
XXXXXXX
BBBBBBBB



