# Generated by Django 3.2.9 on 2022-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_create_articleviews_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=100)),
            ],
        ),
    ]
