# Generated by Django 3.2.9 on 2022-03-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_star_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star_Rating',
        ),
    ]
