BBBB BBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB BBBBB gettext(u'Comment discarded') XBBBBBBBBXXXXXXXX
  XXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXX
      BBBBB BBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Comment can't be verified.") XXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sorry, your comment has been automatically discarded.') XXXXXXXX
      BBBBBBBB BBBBBBB
    XXXXXX
  XXXXXXX
XXXXXXX
