BBBB BBBB
BBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXBBBBB BBBBB
                     gettext(u'Please enter your email to post a comment') BBBBBBBB BBBBBXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
