XXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
BBBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
        XXXXXXXXXXX XXXXXXXXBBBBB BBBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXX X X XX X XXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBBB
XXXXXXXXX
