BBBB BBBBBBBBBBBB
BBBB BBBB
XXXXXXXX XXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBXXXX XXXXBBBBBBBB BBBBBBBBBBBBBBBBBBBXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXX XXXXXXXBBBBB BBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXBBBBBBBB BBBBBBBBBBBBBBXX
        XXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBXXBBBBBBBB BBBBBBBBBBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u' نظرات ') XXXXXXX
        XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBXXXXXXX
        XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXX
        BBBBB
    XXXXXX
    BBBBB BBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
         gettext(u'نظر خود را بیان کنید...') 
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXX
         gettext(u'به این نظر پاسخ دهید...') 
        BBB BBBBBBB BB BBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBB
    XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
        BBBBB BBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBB BBBBB
        BBBBBBBB BBBBBBBBBB
    BBBBB
XXXXXXXXXX
