BBBB BBBBBBBBBBBB
BBBB BBBB



XXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXBBBBXXXXX XXXXBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX X
        BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXX XXXXX  X XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
              
          BB BBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBB
          XXXX
        XXXXXX
        XXXXXX
    BBBB
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX
        XXXXXX
        XXXXXX
    BBBBB

    BBBBB BBBBBBBBBBBBBBB
    BBBBBBBBBBBBBB BBBBBBB
    BBBBBBBB BBBBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBB BB BBBBBBBB
    XXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBBXX
        XXXXXXX
            BBBBBBBBBBBBBBB BBBBBBB BB BBBBBBBBBBB
            XBB BBBBBBBBBBBBXBBBBXXXXBBBBB


            XXBB BBBBBBBBBBBBXBBBBXXXXBBBBBX
            BB BBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Edited') XX gettext(u' %(edited_time)s ویرایش شده:  قبل ')  SSSSSSSSSSSSSSS SSSSSS SSSS  SSS XXXXXXX
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Posted') XX gettext(u' %(posted_time)s قبل ')  SSSSSSSSSSSSSSS SSS XXXXXXX
            BBBBB
            BBBBBBBBBBBBBBBBBB BBBBBBB BBBB BB BBBBBBBBBB
            BB BBBBBBBBBBBB BB BBBB
                X BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBB BBBBBBBBBB
                X BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBB
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBB
                BBBBB
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB
            BB BBBBBBBBBBBBBBBBB
                BBBBBBBBBBBBBBBBB BBBBBBB BBBB BB BBBBBBBBBBB
                X
                XX XXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBXXX XXXXXXXX XXXXBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXX
                     ngettext(u' پاسخ ', u' پاسخ ها ', count)  SSSS  PPPP PP 
                XXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBXXXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXX
                BB BBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
                    XXXXXX
                BBBBB
            BBBBB
        XXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB
    XXXXXX
XXXXXX

