BBBB BBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            
        BBBBBB
    XXXXXX
BBBBB
BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBB BB BBBBBBBBB
        BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBB
    BBBBB
BBBBBB
XX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
