BBBB BBBB
BBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBB BBBBBXXXXX XXX XXXXXBBBBBBBB BBBBBXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBB BBBBBBBXXX XX XXX XXXXXBBBBBBBB BBBBBBB XXXXXXXXXFFFFFFFFFFFXXXXXXXXXX
            XX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                
            BBBB
                
            BBBBB
            XXXXX XXXXXX
        XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBXXX XXXXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX gettext(u' بستن ') XXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBXXX XXXXXXXXXXBBBBBBBB BBBBBBBBBBBXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u' حذف ') XXXXXXX
        XXXXXXXXX
    XXXXXX
XXXXXXX
