BBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBXXXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBXX
            XX XXXXXXBBBBBBBBBBBBBBB BBBBBBBXX
                XXXX XXXXXXXBBBBB BBBBBBBBBXXXXXBBBBBBBB BBBBBBBBBX
                     XXXXXBBBBBBBBBBBB BBBBBBBX XXXXXBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
            XXXX
        XXXXXX
    BBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB
    BB BBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    BBBBB
XXXXXX
