BBBB BBBBBBBBBBBB
BBBB BBBB
XXXXXXX XXXXXXX gettext(u' حذف نظر ') X XXXXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXX
BBBBB BBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
     XXXXXXXXXXX XXXXXXXXBBBBB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX X X X XX XXXXXXXXXXXXXX
    XXXXX XXXXXX XXXXXX X X X XXX XXXXX X X X XXXXXXXXX XXXXX X X X X XXXXXXX X X X X X XXXXXXXXXXXX
    XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBBBB
XXXXXXXXX
