BBBB BBBBBBBBBBBB
BBBB BBBB
XX XXXXXXX gettext(u' ویرایش نظر ') X XXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBX
   XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXX
BBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX
     XXXXXXXXBBBBB BBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXX XXXXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXXXXXXXXXX
    XXXXX XXXXXXXX XXXXXXXXX XXXXX X X X X XXXX XXXXX X XXX XXXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBB
XXXX
