BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Page navigation')  XXXXXXXXXXX XXXXXX
     gettext(u'first') 
     gettext(u'last') 
     gettext(u'Next') 
     gettext(u'Previous') 
    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXX
                XXXX
            XXXXX
        BBBB
            XXX XXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX
            XXXXX
        BBBBB
        BB BBBBBBBBBBBBBBB B B
            XXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB

        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB BB BBBB
                XXX XXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXX
                XXXXX
            BBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                XXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBB
        BBBBBB

        BB BBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB

        BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXX
                XXXX
            XXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXX
        BBBB
            XXX XXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX XXXX
            XXXXX
        BBBBB
    XXXXX
XXXXXX
