BBBB BBBBBBBBBBBB
BBBB BBBB
XXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Flag rejected') BBBB gettext(u'Reject the flag') BBBBBX XXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX

BBBBB BBBBBBBBBBBBBBB
XXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
     XXXXXXXXXXX XXXXXXXXBBBBB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX X XXX XXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX
     XXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX
     XX XXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XXXXXX XXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XXXXXX XXXXXXXXX
       XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
     XXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBBBB
XXXXXXXXX
