BBBB BBBBBBBBBBBB
BBBB BBBB
XXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Flag resolved') BBBB gettext(u'Resolve the flag') BBBBBX XXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBXXX XXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX

BBBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
     XXXXXXXXXXX XXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB
XXXXXXXXX
