BB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
        XXXXX
        XXXX
            BB BBBBBBBBBBBB BB BBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB
        XXXXX
    XXXXX
BBBB
    BB BBBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
        XXXXXX
    BBBBB
BBBBB
