BBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBXX
        BBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX

                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXX
        XXXXXXXXX
    XXXXXXX
XXXXXX
