BBBB BBBB
XX XXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXBBBBBBBB BBBBBBBBBBBX XXXXXXXX XXXXXXX gettext(u'Permalink to this comment') XX
    BBBBB BBBBBBBBBBBB
    X
    BBBBBBBB BBBBBBBBBBBB
XXXX
