XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XX
    BB BBBBBBBBBBBBBXXXXXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFXXXXXX
    BBBBB
    BBB BBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBB XXXXXXBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB XXXXXXBBBBBBBB BBBBB BB BBBBBB BBBBBBBBBBBBBBBB XXXXXXBBBBBBBBBBBXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBB BBBBB BB BBBB
                XXXXBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBB XXXXXXBBBBBBB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBB XXXXXXBBBBBXBBBB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
                    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBBBBBBBB
                        
                    BBBB
                        
                        BB BBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                            
                        BBBBB
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXFFFFXXXXXX
                    BBBBB
                XXXXXX
            BBBBBB
        XXXXXX
    BBBBBB
XXXXXXXXXXX
