BBBB BBBB
BBB BBBBBBBBBBBBBB BBBBBBBBBBBBB  BB BBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX
BBBB
XX XXXXXXXXXXXXXX XXXXXXX gettext(u'flag') XX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXX
BBBBB
