BBBB BBBB
BBBB BBBBBBBBBBBB
XXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Remove flag') BBBB gettext(u'Report comment') BBBBBXX
BBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXBBBBBX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
     XXXXXXXXBBBBB BBBBBBBBBBBBBBBXXXXXXXBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX XXXXXX XXX X X X X XXX XXXXXXXX XXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBBBB
XXXXXXX
