BBBB BBBB
BBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB BBBBB gettext(u'Please select a reason for flagging') BBBBBBBB BBBBBXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BBBBBBBBBBBBBBBBBBB BB BBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBB BB BBBBBBB
                    XXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXX
                    BBBBBB
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Flag') 
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

