XXXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXX XXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
        X

        XXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

    XXXXXXXX
        XXXXXXXXXXXX X

            XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXX
                XXXXXX XXXXXXX
                XXXXXXXXXX XXXXX
                XXXXXXXX XXXXX
                XXXXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXXXX XXXXX
                XXXXXXXXX XXX
                XXXXXXXXXXXXXXXX XX
                XXXXXXXXXXX XXX
                XXXXXXX X
                    X XXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                    X XXXXX XXXXXX XXXXX XXXXXXXXX XXXXXX XX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXX XXXXX XX
                    X XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX X
                X
            XXX

            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXX XXX X XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
