XXXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXX XXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXXXX X
            XXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXX XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

    XXXXXXXX
        XXXXXXXXXXXX X

            XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXX
                XXXXXX XXXXXXX
                XXXXXXXX XXXXX
                XXXXXXX XXXXXX
                XXXXXXXXX XXXXX
                XXXXXXXXXXX X
                    XXXXXXXXX XXXXXXXXXX X
                        XXX X X XXXXXXXXXXXXX

                        XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXX
                        XXX

                        XXXXXX XXXXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXX X XXX XXXXXXXXXX

                    XXXXXX X
                        XXXXX XXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXX
                        XX
                        XXXXX XXXXXXXXXX X
                            XXXXXXXXXXXXXXX
                        X
                    XX
                XX
                XXXXXXX X
                    X XXXXX XXXXXXX XXXXX XXXXXX XX
                    X XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXX XX
                    X XXXXX XXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXX XXXXXX XXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                        X
                    XX
                    X XXXXX XXXXXXXX XXXXX XXXXXXXXX XXXXXX XXX
                        XXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                            XXXXXX XXXXXXXXXXXXXXXX X XXXX X
                    X
                X
            XXX

        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
