XXXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXXX XXXX XX XXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXXX XXXX XX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

    XXXXXXXX
        XXXXXXXXXXXX X

            XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXX
                XXXXXX XXXXXXX
                XXXXXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXXXXXXX XXXXX
                XXXXXXXXX XXX
                XXXXXXXXXX XX
                XXXXXXXXXXX X
                    XXXXXXXXX XXXXXXXXXXXXXXXX X
                        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXX
                        XXXXXX X
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX
                    X
                XX
                XXXXXXX X
                    X XXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                    X XXXXX XXXXXX XXXXX XXXXXXXXX XXXXXX XX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XX
                    X XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXX X
                X
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXX

        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
