XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXX X

        XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXX
            XXXXXX XXXXXXX
            XXXXXXXXX XXXXX

            XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXX XXXXXXXXX X XXXXXXXXXX
            XX

            XXXXXXXXXXX X
                XXXXXXXXX XXXXXXXXXX X
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXX
                X
            XX

            XXXXXXX X
                X XXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                X XXXXX XXXXXX XXXXX XXXXXXXXX XXXXXX XX XX
                X XXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXX XXX XX
                X XXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XX
                X XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXX XXXXX X
            XX

            XXXXXXXXXXXX XXXXXXXXXX X
                XXX XXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX

                XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXX XXX X
                        XX XXXXX XX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXXX X
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                        XXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXX XXXX

                        XX XXXXXX XX XXXXX
                        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                        XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
                    X
                XXX
            X
        XXX

    XXX
XXXXXXXXX
XXXXXXX
XXXXXXX
