BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBB BB BBBBBBBB
    XX XXXXXXX gettext(u'like') X XXXXXXXBBBBB BBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXXXXXXX XXXXXXX
        BBBB
        X XXXXXXXXXXXXXX
        BBBBB
    X
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
    XX XXXXXXX gettext(u'dislike') X XXXXXXXBBBBB BBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXXXXXXX XXXXXXX
        BBBB
        X XXXXXXXXXXXXXX
        BBBBB
    X
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
    XXXXXX
