BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBB
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX
BBBBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXX
    BBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBB
    BBBBBBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXX
    XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBXXXXXX
            BBB BBBB BB BBBBBBBBBBB
            XXXX XXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBB BBBBBBBBBXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX FFFF  FFFFFFFFF  FFFFFFFFFFFFFFFFXXXXX
                    XXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXX
                    XXXXX XXX XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        
                        BBBB
                        
                        BBBBB
                    XXXX

                     FFFFFFFFFFF
                XXXX
            XXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXX
                BBBBBB
            XXXXXX
            XXXX XXXXXXXXXX
            XXX XXXXXXXXXXXXXX
            BBBBB
                XX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX XX XXX XXXX XXXX XXXXX
                XXXX
            BBBBBB

            XXXX XXXXXXXX
            BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXX X
                   XXXXXX BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB XXXXX XXX XXXX XXXXXX XXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXX XXX XXXXX
                    XXXXXX XXXX
                BBBBB
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB