BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB


BBBBB  BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXX
BBBBBBBB

BBBBB BBBB

  XXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXXXXX XX XXX XX XXXXXX XXXX XXX XXX XXXX XXXXX XX XXXX XX X XXXXXXX XXX X XXXX XXX XXXX XX XXX XX XXXX XX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                            XXXX X X X X X X X X X X X X X X XXXX
                            XXXX X X XX XXXXX XXXXXXX XXXX X XXXX
                            XXXX X X X X X X X X X X X X X X XXXX
                            XXXX XXXX XXXX XX XXXXXXXXXXXXXX XXXX XX XXXXXXXXX
                            XXXX XX XXXX XXXX XXXX XXXXXXXXXXX XXXX XX XXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XX XXX XX XXX XXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XX XXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX
                                XXXXXX
                                XXX XX
                                XXXX XXXXXX XXXXXXX XXXXXXXXXX
                                XXXXXXX
                                XXXX XXXX XX XXXX XXXX XXXXX XXXX XXX XXXX XXX XXXXXXX
                                XXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                                        XX XXXXXXXX XXXX XXXXX XXXX XX XX
                                        XXX XX
                                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                                XXXX XXXXXX XXXXX XXXXXXXXXX
                                XXXXXXX
                                XXXX XXXX XX XXXX XXXX XXXXX XXXX XXX XXXX XXXXX XXXXX
                                XXXX XX XXXXX XXXXXXXXXX XXX XXXXXXX
                                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXX XXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXX
BBBBBBBB