BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB


BBBBB  BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXX FFFFFFFFF  FFFFFFFFFFFFFFFFXXXXX
                            XXXXX XXXXXXXXXXXXX
                                XXXXX XXX XXXX
                                XX XXXXXXXXXXXXX XXXX
                                 FFFFFFFFFF
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXX
BBBBBBBB

BBBBB BBBB
     XXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                         FFFF  FFFFFFFFFF
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
BBBBBBBB