BBBB BBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBB
        BBBBBBBBB
        BB BBB BBBBBBBBB
        BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Change selected %(model)s') SSSSSS SSSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Change') XX
        XXXX
        BBBBB
        BB BBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXX
            XXXXXXX gettext(u'Add another %(model)s') SSS SSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Add') XX
        XXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Delete selected %(model)s') SSSSSS SSSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Delete') XX
        XXXX
        BBBBB
        BBBBB
        BBBBBBBBBBBB
    BBBBBBBB
XXXXXX
