BBBB BBBB
BBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXBBBBB BBBBB gettext(u'Please insert your email to follow this thread') BBBBBBBB BBBBBXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX

                            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                BBBBBBBB BBBBBBBBBBB
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Follow') 
                        XXXXXXX XXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX
                        XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

