XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBXXXXXXXXXXXXXXX
        BBB BBBBBBBB BB BBBBBBBBB

            BB BBBBBBBBBBBBBBB BB BBBB
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBB
                XXXXX

            BBBBB

        BBBBBB
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBXXXXXXXX X XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXX XX XXXXXXXXXXX
    XXXXX
XXXXXX