

XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB
        XXXXX
    BBBBBB
XXXXX